export const SEED_BOOKS: { title: string; author: string; genre: string }[] = [
  // Literary Fiction
  { title: "Normal People", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Conversations with Friends", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Beautiful World, Where Are You", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Intermezzo", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Piranesi", author: "Susanna Clarke", genre: "Literary Fiction" },
  { title: "The Corrections", author: "Jonathan Franzen", genre: "Literary Fiction" },
  { title: "A Little Life", author: "Hanya Yanagihara", genre: "Literary Fiction" },
  { title: "Olive Kitteridge", author: "Elizabeth Strout", genre: "Literary Fiction" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", genre: "Literary Fiction" },
  { title: "The God of Small Things", author: "Arundhati Roy", genre: "Literary Fiction" },
  { title: "Never Let Me Go", author: "Kazuo Ishiguro", genre: "Literary Fiction" },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro", genre: "Literary Fiction" },
  { title: "On Earth We're Briefly Gorgeous", author: "Ocean Vuong", genre: "Literary Fiction" },
  { title: "Demon Copperhead", author: "Barbara Kingsolver", genre: "Literary Fiction" },

  // Fantasy
  { title: "The Name of the Wind", author: "Patrick Rothfuss", genre: "Fantasy" },
  { title: "The Way of Kings", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "A Court of Thorns and Roses", author: "Sarah J. Maas", genre: "Fantasy" },
  { title: "Throne of Glass", author: "Sarah J. Maas", genre: "Fantasy" },
  { title: "Fourth Wing", author: "Rebecca Yarros", genre: "Fantasy" },
  { title: "The Priory of the Orange Tree", author: "Samantha Shannon", genre: "Fantasy" },
  { title: "The House in the Cerulean Sea", author: "TJ Klune", genre: "Fantasy" },
  { title: "Jonathan Strange & Mr Norrell", author: "Susanna Clarke", genre: "Fantasy" },
  { title: "The Night Circus", author: "Erin Morgenstern", genre: "Fantasy" },
  { title: "American Gods", author: "Neil Gaiman", genre: "Fantasy" },
  { title: "The Poppy War", author: "R.F. Kuang", genre: "Fantasy" },
  { title: "Babel", author: "R.F. Kuang", genre: "Fantasy" },
  { title: "The Stormlight Archive: Words of Radiance", author: "Brandon Sanderson", genre: "Fantasy" },

  // Romance
  { title: "The Hating Game", author: "Sally Thorne", genre: "Romance" },
  { title: "Beach Read", author: "Emily Henry", genre: "Romance" },
  { title: "People We Meet on Vacation", author: "Emily Henry", genre: "Romance" },
  { title: "Book Lovers", author: "Emily Henry", genre: "Romance" },
  { title: "Happy Place", author: "Emily Henry", genre: "Romance" },
  { title: "It Ends with Us", author: "Colleen Hoover", genre: "Romance" },
  { title: "Ugly Love", author: "Colleen Hoover", genre: "Romance" },
  { title: "Reminders of Him", author: "Colleen Hoover", genre: "Romance" },
  { title: "November 9", author: "Colleen Hoover", genre: "Romance" },
  { title: "The Spanish Love Deception", author: "Elena Armas", genre: "Romance" },
  { title: "Twisted Love", author: "Ana Huang", genre: "Romance" },
  { title: "The Kiss Quotient", author: "Helen Hoang", genre: "Romance" },
  { title: "Pride and Prejudice", author: "Jane Austen", genre: "Romance" },

  // Sci-Fi
  { title: "Dune", author: "Frank Herbert", genre: "Sci-Fi" },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", genre: "Sci-Fi" },
  { title: "Ender's Game", author: "Orson Scott Card", genre: "Sci-Fi" },
  { title: "The Martian", author: "Andy Weir", genre: "Sci-Fi" },
  { title: "Project Hail Mary", author: "Andy Weir", genre: "Sci-Fi" },
  { title: "Recursion", author: "Blake Crouch", genre: "Sci-Fi" },
  { title: "Dark Matter", author: "Blake Crouch", genre: "Sci-Fi" },
  { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", genre: "Sci-Fi" },
  { title: "Flowers for Algernon", author: "Daniel Keyes", genre: "Sci-Fi" },
  { title: "Kindred", author: "Octavia Butler", genre: "Sci-Fi" },
  { title: "Parable of the Sower", author: "Octavia Butler", genre: "Sci-Fi" },
  { title: "The Long Way to a Small, Angry Planet", author: "Becky Chambers", genre: "Sci-Fi" },
  { title: "Children of Time", author: "Adrian Tchaikovsky", genre: "Sci-Fi" },
  { title: "1984", author: "George Orwell", genre: "Sci-Fi" },

  // Mystery/Thriller
  { title: "Gone Girl", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "Sharp Objects", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "Dark Places", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", genre: "Mystery/Thriller" },
  { title: "The Woman in the Window", author: "A.J. Finn", genre: "Mystery/Thriller" },
  { title: "Behind Closed Doors", author: "B.A. Paris", genre: "Mystery/Thriller" },
  { title: "The Silent Patient", author: "Alex Michaelides", genre: "Mystery/Thriller" },
  { title: "The Maidens", author: "Alex Michaelides", genre: "Mystery/Thriller" },
  { title: "In the Woods", author: "Tana French", genre: "Mystery/Thriller" },
  { title: "The Secret History", author: "Donna Tartt", genre: "Mystery/Thriller" },
  { title: "And Then There Were None", author: "Agatha Christie", genre: "Mystery/Thriller" },
  { title: "The Thursday Murder Club", author: "Richard Osman", genre: "Mystery/Thriller" },
  { title: "Verity", author: "Colleen Hoover", genre: "Mystery/Thriller" },
  { title: "The 7½ Deaths of Evelyn Hardcastle", author: "Stuart Turton", genre: "Mystery/Thriller" },

  // Historical Fiction
  { title: "The Pillars of the Earth", author: "Ken Follett", genre: "Historical Fiction" },
  { title: "All the Light We Cannot See", author: "Anthony Doerr", genre: "Historical Fiction" },
  { title: "The Alice Network", author: "Kate Quinn", genre: "Historical Fiction" },
  { title: "The Rose Code", author: "Kate Quinn", genre: "Historical Fiction" },
  { title: "The Nightingale", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "The Four Winds", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "Outlander", author: "Diana Gabaldon", genre: "Historical Fiction" },
  { title: "Lincoln in the Bardo", author: "George Saunders", genre: "Historical Fiction" },
  { title: "The Name of the Rose", author: "Umberto Eco", genre: "Historical Fiction" },
  { title: "Wolf Hall", author: "Hilary Mantel", genre: "Historical Fiction" },
  { title: "The Kite Runner", author: "Khaled Hosseini", genre: "Historical Fiction" },
  { title: "A Thousand Splendid Suns", author: "Khaled Hosseini", genre: "Historical Fiction" },
  { title: "The Book Thief", author: "Markus Zusak", genre: "Historical Fiction" },

  // YA
  { title: "The Hunger Games", author: "Suzanne Collins", genre: "YA" },
  { title: "Catching Fire", author: "Suzanne Collins", genre: "YA" },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", genre: "YA" },
  { title: "The Fault in Our Stars", author: "John Green", genre: "YA" },
  { title: "Turtles All the Way Down", author: "John Green", genre: "YA" },
  { title: "The Perks of Being a Wallflower", author: "Stephen Chbosky", genre: "YA" },
  { title: "Six of Crows", author: "Leigh Bardugo", genre: "YA" },
  { title: "Shadow and Bone", author: "Leigh Bardugo", genre: "YA" },
  { title: "An Ember in the Ashes", author: "Sabaa Tahir", genre: "YA" },
  { title: "The Cruel Prince", author: "Holly Black", genre: "YA" },
  { title: "Children of Blood and Bone", author: "Tomi Adeyemi", genre: "YA" },
  { title: "They Both Die at the End", author: "Adam Silvera", genre: "YA" },
  { title: "Eleanor & Park", author: "Rainbow Rowell", genre: "YA" },
  { title: "The Maze Runner", author: "James Dashner", genre: "YA" },

  // Horror/Gothic
  { title: "Frankenstein", author: "Mary Shelley", genre: "Horror/Gothic" },
  { title: "Dracula", author: "Bram Stoker", genre: "Horror/Gothic" },
  { title: "The Haunting of Hill House", author: "Shirley Jackson", genre: "Horror/Gothic" },
  { title: "We Have Always Lived in the Castle", author: "Shirley Jackson", genre: "Horror/Gothic" },
  { title: "The Shining", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "It", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Pet Sematary", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", genre: "Horror/Gothic" },
  { title: "Plain Bad Heroines", author: "Emily M. Danforth", genre: "Horror/Gothic" },
  { title: "The Troop", author: "Nick Cutter", genre: "Horror/Gothic" },
  { title: "My Best Friend's Exorcism", author: "Grady Hendrix", genre: "Horror/Gothic" },
  { title: "House of Leaves", author: "Mark Z. Danielewski", genre: "Horror/Gothic" },
  { title: "Rebecca", author: "Daphne du Maurier", genre: "Horror/Gothic" },
];
