export const SEED_BOOKS: { title: string; author: string; genre: string }[] = [
  // ===================
  // Literary Fiction (~50)
  // ===================
  { title: "Normal People", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Conversations with Friends", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Beautiful World, Where Are You", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Intermezzo", author: "Sally Rooney", genre: "Literary Fiction" },
  { title: "Piranesi", author: "Susanna Clarke", genre: "Literary Fiction" },
  { title: "The Corrections", author: "Jonathan Franzen", genre: "Literary Fiction" },
  { title: "A Little Life", author: "Hanya Yanagihara", genre: "Literary Fiction" },
  { title: "Olive Kitteridge", author: "Elizabeth Strout", genre: "Literary Fiction" },
  { title: "To Kill a Mockingbird", author: "Harper Lee", genre: "Literary Fiction" },
  { title: "The God of Small Things", author: "Arundhati Roy", genre: "Literary Fiction" },
  { title: "Never Let Me Go", author: "Kazuo Ishiguro", genre: "Literary Fiction" },
  { title: "The Remains of the Day", author: "Kazuo Ishiguro", genre: "Literary Fiction" },
  { title: "On Earth We're Briefly Gorgeous", author: "Ocean Vuong", genre: "Literary Fiction" },
  { title: "Demon Copperhead", author: "Barbara Kingsolver", genre: "Literary Fiction" },
  // NEW Literary Fiction
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Literary Fiction" },
  { title: "Beloved", author: "Toni Morrison", genre: "Literary Fiction" },
  { title: "Song of Solomon", author: "Toni Morrison", genre: "Literary Fiction" },
  { title: "The Goldfinch", author: "Donna Tartt", genre: "Literary Fiction" },
  { title: "Middlesex", author: "Jeffrey Eugenides", genre: "Literary Fiction" },
  { title: "The Virgin Suicides", author: "Jeffrey Eugenides", genre: "Literary Fiction" },
  { title: "Atonement", author: "Ian McEwan", genre: "Literary Fiction" },
  { title: "White Teeth", author: "Zadie Smith", genre: "Literary Fiction" },
  { title: "The Brief Wondrous Life of Oscar Wao", author: "Junot Diaz", genre: "Literary Fiction" },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", genre: "Literary Fiction" },
  { title: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", genre: "Literary Fiction" },
  { title: "The Road", author: "Cormac McCarthy", genre: "Literary Fiction" },
  { title: "Blood Meridian", author: "Cormac McCarthy", genre: "Literary Fiction" },
  { title: "The Sympathizer", author: "Viet Thanh Nguyen", genre: "Literary Fiction" },
  { title: "Hamnet", author: "Maggie O'Farrell", genre: "Literary Fiction" },
  { title: "Shuggie Bain", author: "Douglas Stuart", genre: "Literary Fiction" },
  { title: "The Overstory", author: "Richard Powers", genre: "Literary Fiction" },
  { title: "Pachinko", author: "Min Jin Lee", genre: "Literary Fiction" },
  { title: "My Year of Rest and Relaxation", author: "Ottessa Moshfegh", genre: "Literary Fiction" },
  { title: "The Vanishing Half", author: "Brit Bennett", genre: "Literary Fiction" },
  { title: "Klara and the Sun", author: "Kazuo Ishiguro", genre: "Literary Fiction" },
  { title: "The Unbearable Lightness of Being", author: "Milan Kundera", genre: "Literary Fiction" },
  { title: "Norwegian Wood", author: "Haruki Murakami", genre: "Literary Fiction" },
  { title: "Kafka on the Shore", author: "Haruki Murakami", genre: "Literary Fiction" },
  { title: "The Poisonwood Bible", author: "Barbara Kingsolver", genre: "Literary Fiction" },
  { title: "Homegoing", author: "Yaa Gyasi", genre: "Literary Fiction" },
  { title: "Life of Pi", author: "Yann Martel", genre: "Literary Fiction" },
  { title: "The Color Purple", author: "Alice Walker", genre: "Literary Fiction" },
  { title: "Circe", author: "Madeline Miller", genre: "Literary Fiction" },
  { title: "The Song of Achilles", author: "Madeline Miller", genre: "Literary Fiction" },
  { title: "Lessons in Chemistry", author: "Bonnie Garmus", genre: "Literary Fiction" },
  { title: "Tomorrow, and Tomorrow, and Tomorrow", author: "Gabrielle Zevin", genre: "Literary Fiction" },
  { title: "The Dutch House", author: "Ann Patchett", genre: "Literary Fiction" },
  { title: "Bel Canto", author: "Ann Patchett", genre: "Literary Fiction" },
  { title: "The Secret Life of Bees", author: "Sue Monk Kidd", genre: "Literary Fiction" },
  { title: "Where the Crawdads Sing", author: "Delia Owens", genre: "Literary Fiction" },

  // ===================
  // Fantasy (~60)
  // ===================
  { title: "The Name of the Wind", author: "Patrick Rothfuss", genre: "Fantasy" },
  { title: "The Way of Kings", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "A Court of Thorns and Roses", author: "Sarah J. Maas", genre: "Fantasy" },
  { title: "Throne of Glass", author: "Sarah J. Maas", genre: "Fantasy" },
  { title: "Fourth Wing", author: "Rebecca Yarros", genre: "Fantasy" },
  { title: "The Priory of the Orange Tree", author: "Samantha Shannon", genre: "Fantasy" },
  { title: "The House in the Cerulean Sea", author: "TJ Klune", genre: "Fantasy" },
  { title: "Jonathan Strange & Mr Norrell", author: "Susanna Clarke", genre: "Fantasy" },
  { title: "The Night Circus", author: "Erin Morgenstern", genre: "Fantasy" },
  { title: "American Gods", author: "Neil Gaiman", genre: "Fantasy" },
  { title: "The Poppy War", author: "R.F. Kuang", genre: "Fantasy" },
  { title: "Babel", author: "R.F. Kuang", genre: "Fantasy" },
  { title: "The Stormlight Archive: Words of Radiance", author: "Brandon Sanderson", genre: "Fantasy" },
  // NEW Fantasy
  { title: "The Hobbit", author: "J.R.R. Tolkien", genre: "Fantasy" },
  { title: "The Fellowship of the Ring", author: "J.R.R. Tolkien", genre: "Fantasy" },
  { title: "The Two Towers", author: "J.R.R. Tolkien", genre: "Fantasy" },
  { title: "The Return of the King", author: "J.R.R. Tolkien", genre: "Fantasy" },
  { title: "A Game of Thrones", author: "George R.R. Martin", genre: "Fantasy" },
  { title: "A Clash of Kings", author: "George R.R. Martin", genre: "Fantasy" },
  { title: "A Storm of Swords", author: "George R.R. Martin", genre: "Fantasy" },
  { title: "The Eye of the World", author: "Robert Jordan", genre: "Fantasy" },
  { title: "The Final Empire", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "The Lies of Locke Lamora", author: "Scott Lynch", genre: "Fantasy" },
  { title: "The Blade Itself", author: "Joe Abercrombie", genre: "Fantasy" },
  { title: "Assassin's Apprentice", author: "Robin Hobb", genre: "Fantasy" },
  { title: "The Color of Magic", author: "Terry Pratchett", genre: "Fantasy" },
  { title: "Guards! Guards!", author: "Terry Pratchett", genre: "Fantasy" },
  { title: "Good Omens", author: "Terry Pratchett", genre: "Fantasy" },
  { title: "Stardust", author: "Neil Gaiman", genre: "Fantasy" },
  { title: "Neverwhere", author: "Neil Gaiman", genre: "Fantasy" },
  { title: "The Ocean at the End of the Lane", author: "Neil Gaiman", genre: "Fantasy" },
  { title: "A Wizard of Earthsea", author: "Ursula K. Le Guin", genre: "Fantasy" },
  { title: "The Lion, the Witch and the Wardrobe", author: "C.S. Lewis", genre: "Fantasy" },
  { title: "Uprooted", author: "Naomi Novik", genre: "Fantasy" },
  { title: "Spinning Silver", author: "Naomi Novik", genre: "Fantasy" },
  { title: "The Invisible Life of Addie LaRue", author: "V.E. Schwab", genre: "Fantasy" },
  { title: "A Darker Shade of Magic", author: "V.E. Schwab", genre: "Fantasy" },
  { title: "The Fifth Season", author: "N.K. Jemisin", genre: "Fantasy" },
  { title: "The City We Became", author: "N.K. Jemisin", genre: "Fantasy" },
  { title: "Mistborn: The Well of Ascension", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "The Atlas Six", author: "Olivie Blake", genre: "Fantasy" },
  { title: "House of Salt and Sorrows", author: "Erin A. Craig", genre: "Fantasy" },
  { title: "A Court of Mist and Fury", author: "Sarah J. Maas", genre: "Fantasy" },
  { title: "The Bear and the Nightingale", author: "Katherine Arden", genre: "Fantasy" },
  { title: "The Starless Sea", author: "Erin Morgenstern", genre: "Fantasy" },
  { title: "Eragon", author: "Christopher Paolini", genre: "Fantasy" },
  { title: "The Princess Bride", author: "William Goldman", genre: "Fantasy" },
  { title: "Iron Flame", author: "Rebecca Yarros", genre: "Fantasy" },
  { title: "The Sword of Kaigen", author: "M.L. Wang", genre: "Fantasy" },
  { title: "Warbreaker", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "The Goblin Emperor", author: "Katherine Addison", genre: "Fantasy" },
  { title: "Graceling", author: "Kristin Cashore", genre: "Fantasy" },
  { title: "Sorcerer to the Crown", author: "Zen Cho", genre: "Fantasy" },
  { title: "The Rage of Dragons", author: "Evan Winter", genre: "Fantasy" },
  { title: "The Black Prism", author: "Brent Weeks", genre: "Fantasy" },
  { title: "Gardens of the Moon", author: "Steven Erikson", genre: "Fantasy" },
  { title: "The Sword of Shannara", author: "Terry Brooks", genre: "Fantasy" },
  { title: "Elantris", author: "Brandon Sanderson", genre: "Fantasy" },
  { title: "The Magicians", author: "Lev Grossman", genre: "Fantasy" },
  { title: "Howl's Moving Castle", author: "Diana Wynne Jones", genre: "Fantasy" },

  // ===================
  // Romance (~60)
  // ===================
  { title: "The Hating Game", author: "Sally Thorne", genre: "Romance" },
  { title: "Beach Read", author: "Emily Henry", genre: "Romance" },
  { title: "People We Meet on Vacation", author: "Emily Henry", genre: "Romance" },
  { title: "Book Lovers", author: "Emily Henry", genre: "Romance" },
  { title: "Happy Place", author: "Emily Henry", genre: "Romance" },
  { title: "It Ends with Us", author: "Colleen Hoover", genre: "Romance" },
  { title: "Ugly Love", author: "Colleen Hoover", genre: "Romance" },
  { title: "Reminders of Him", author: "Colleen Hoover", genre: "Romance" },
  { title: "November 9", author: "Colleen Hoover", genre: "Romance" },
  { title: "The Spanish Love Deception", author: "Elena Armas", genre: "Romance" },
  { title: "Twisted Love", author: "Ana Huang", genre: "Romance" },
  { title: "The Kiss Quotient", author: "Helen Hoang", genre: "Romance" },
  { title: "Pride and Prejudice", author: "Jane Austen", genre: "Romance" },
  // NEW Romance
  { title: "Sense and Sensibility", author: "Jane Austen", genre: "Romance" },
  { title: "Emma", author: "Jane Austen", genre: "Romance" },
  { title: "Persuasion", author: "Jane Austen", genre: "Romance" },
  { title: "Jane Eyre", author: "Charlotte Bronte", genre: "Romance" },
  { title: "Wuthering Heights", author: "Emily Bronte", genre: "Romance" },
  { title: "The Notebook", author: "Nicholas Sparks", genre: "Romance" },
  { title: "A Walk to Remember", author: "Nicholas Sparks", genre: "Romance" },
  { title: "Me Before You", author: "Jojo Moyes", genre: "Romance" },
  { title: "The Rosie Project", author: "Graeme Simsion", genre: "Romance" },
  { title: "Red, White & Royal Blue", author: "Casey McQuiston", genre: "Romance" },
  { title: "One Last Stop", author: "Casey McQuiston", genre: "Romance" },
  { title: "The Flatshare", author: "Beth O'Leary", genre: "Romance" },
  { title: "The Love Hypothesis", author: "Ali Hazelwood", genre: "Romance" },
  { title: "Love on the Brain", author: "Ali Hazelwood", genre: "Romance" },
  { title: "Check & Mate", author: "Ali Hazelwood", genre: "Romance" },
  { title: "The Bride Test", author: "Helen Hoang", genre: "Romance" },
  { title: "Things We Never Got Over", author: "Lucy Score", genre: "Romance" },
  { title: "The Wall of Winnipeg and Me", author: "Mariana Zapata", genre: "Romance" },
  { title: "Kulti", author: "Mariana Zapata", genre: "Romance" },
  { title: "From Blood and Ash", author: "Jennifer L. Armentrout", genre: "Romance" },
  { title: "It Happened One Summer", author: "Tessa Bailey", genre: "Romance" },
  { title: "Hook, Line, and Sinker", author: "Tessa Bailey", genre: "Romance" },
  { title: "The Deal", author: "Elle Kennedy", genre: "Romance" },
  { title: "Birthday Girl", author: "Penelope Douglas", genre: "Romance" },
  { title: "Punk 57", author: "Penelope Douglas", genre: "Romance" },
  { title: "Funny Story", author: "Emily Henry", genre: "Romance" },
  { title: "Maybe Someday", author: "Colleen Hoover", genre: "Romance" },
  { title: "Confess", author: "Colleen Hoover", genre: "Romance" },
  { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid", genre: "Romance" },
  { title: "Malibu Rising", author: "Taylor Jenkins Reid", genre: "Romance" },
  { title: "Daisy Jones & The Six", author: "Taylor Jenkins Reid", genre: "Romance" },
  { title: "The Proposal", author: "Jasmine Guillory", genre: "Romance" },
  { title: "The Wedding Date", author: "Jasmine Guillory", genre: "Romance" },
  { title: "Shipped", author: "Angie Hockman", genre: "Romance" },
  { title: "Get a Life, Chloe Brown", author: "Talia Hibbert", genre: "Romance" },
  { title: "Act Your Age, Eve Brown", author: "Talia Hibbert", genre: "Romance" },
  { title: "The Unhoneymooners", author: "Christina Lauren", genre: "Romance" },
  { title: "In a Holidaze", author: "Christina Lauren", genre: "Romance" },
  { title: "You Deserve Each Other", author: "Sarah Hogle", genre: "Romance" },
  { title: "The Duchess Deal", author: "Tessa Dare", genre: "Romance" },
  { title: "Vision in White", author: "Nora Roberts", genre: "Romance" },
  { title: "Neon Gods", author: "Katee Robert", genre: "Romance" },
  { title: "The Soulmate Equation", author: "Christina Lauren", genre: "Romance" },
  { title: "Something Wilder", author: "Christina Lauren", genre: "Romance" },
  { title: "Part of Your World", author: "Abby Jimenez", genre: "Romance" },
  { title: "Yours Truly", author: "Abby Jimenez", genre: "Romance" },
  { title: "Just Last Night", author: "Mhairi McFarlane", genre: "Romance" },

  // ===================
  // Sci-Fi (~55)
  // ===================
  { title: "Dune", author: "Frank Herbert", genre: "Sci-Fi" },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", genre: "Sci-Fi" },
  { title: "Ender's Game", author: "Orson Scott Card", genre: "Sci-Fi" },
  { title: "The Martian", author: "Andy Weir", genre: "Sci-Fi" },
  { title: "Project Hail Mary", author: "Andy Weir", genre: "Sci-Fi" },
  { title: "Recursion", author: "Blake Crouch", genre: "Sci-Fi" },
  { title: "Dark Matter", author: "Blake Crouch", genre: "Sci-Fi" },
  { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", genre: "Sci-Fi" },
  { title: "Flowers for Algernon", author: "Daniel Keyes", genre: "Sci-Fi" },
  { title: "Kindred", author: "Octavia Butler", genre: "Sci-Fi" },
  { title: "Parable of the Sower", author: "Octavia Butler", genre: "Sci-Fi" },
  { title: "The Long Way to a Small, Angry Planet", author: "Becky Chambers", genre: "Sci-Fi" },
  { title: "Children of Time", author: "Adrian Tchaikovsky", genre: "Sci-Fi" },
  { title: "1984", author: "George Orwell", genre: "Sci-Fi" },
  // NEW Sci-Fi
  { title: "Brave New World", author: "Aldous Huxley", genre: "Sci-Fi" },
  { title: "Fahrenheit 451", author: "Ray Bradbury", genre: "Sci-Fi" },
  { title: "The Martian Chronicles", author: "Ray Bradbury", genre: "Sci-Fi" },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", genre: "Sci-Fi" },
  { title: "Cat's Cradle", author: "Kurt Vonnegut", genre: "Sci-Fi" },
  { title: "Foundation", author: "Isaac Asimov", genre: "Sci-Fi" },
  { title: "I, Robot", author: "Isaac Asimov", genre: "Sci-Fi" },
  { title: "2001: A Space Odyssey", author: "Arthur C. Clarke", genre: "Sci-Fi" },
  { title: "Childhood's End", author: "Arthur C. Clarke", genre: "Sci-Fi" },
  { title: "Neuromancer", author: "William Gibson", genre: "Sci-Fi" },
  { title: "Snow Crash", author: "Neal Stephenson", genre: "Sci-Fi" },
  { title: "The Dispossessed", author: "Ursula K. Le Guin", genre: "Sci-Fi" },
  { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", genre: "Sci-Fi" },
  { title: "The Man in the High Castle", author: "Philip K. Dick", genre: "Sci-Fi" },
  { title: "Annihilation", author: "Jeff VanderMeer", genre: "Sci-Fi" },
  { title: "The Three-Body Problem", author: "Liu Cixin", genre: "Sci-Fi" },
  { title: "The Dark Forest", author: "Liu Cixin", genre: "Sci-Fi" },
  { title: "Hyperion", author: "Dan Simmons", genre: "Sci-Fi" },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", genre: "Sci-Fi" },
  { title: "Oryx and Crake", author: "Margaret Atwood", genre: "Sci-Fi" },
  { title: "Station Eleven", author: "Emily St. John Mandel", genre: "Sci-Fi" },
  { title: "The Sea of Tranquility", author: "Emily St. John Mandel", genre: "Sci-Fi" },
  { title: "Artemis", author: "Andy Weir", genre: "Sci-Fi" },
  { title: "Upgrade", author: "Blake Crouch", genre: "Sci-Fi" },
  { title: "Red Rising", author: "Pierce Brown", genre: "Sci-Fi" },
  { title: "Old Man's War", author: "John Scalzi", genre: "Sci-Fi" },
  { title: "All Systems Red", author: "Martha Wells", genre: "Sci-Fi" },
  { title: "A Closed and Common Orbit", author: "Becky Chambers", genre: "Sci-Fi" },
  { title: "Dune Messiah", author: "Frank Herbert", genre: "Sci-Fi" },
  { title: "Contact", author: "Carl Sagan", genre: "Sci-Fi" },
  { title: "The Time Machine", author: "H.G. Wells", genre: "Sci-Fi" },
  { title: "The War of the Worlds", author: "H.G. Wells", genre: "Sci-Fi" },
  { title: "Jurassic Park", author: "Michael Crichton", genre: "Sci-Fi" },
  { title: "The Andromeda Strain", author: "Michael Crichton", genre: "Sci-Fi" },
  { title: "Sphere", author: "Michael Crichton", genre: "Sci-Fi" },
  { title: "Ready Player One", author: "Ernest Cline", genre: "Sci-Fi" },
  { title: "Starship Troopers", author: "Robert A. Heinlein", genre: "Sci-Fi" },
  { title: "Stranger in a Strange Land", author: "Robert A. Heinlein", genre: "Sci-Fi" },
  { title: "The Hunger Games: Sunrise on the Reaping", author: "Suzanne Collins", genre: "Sci-Fi" },
  { title: "Rendezvous with Rama", author: "Arthur C. Clarke", genre: "Sci-Fi" },
  { title: "The Forever War", author: "Joe Haldeman", genre: "Sci-Fi" },

  // ===================
  // Mystery/Thriller (~55)
  // ===================
  { title: "Gone Girl", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "Sharp Objects", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "Dark Places", author: "Gillian Flynn", genre: "Mystery/Thriller" },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", genre: "Mystery/Thriller" },
  { title: "The Woman in the Window", author: "A.J. Finn", genre: "Mystery/Thriller" },
  { title: "Behind Closed Doors", author: "B.A. Paris", genre: "Mystery/Thriller" },
  { title: "The Silent Patient", author: "Alex Michaelides", genre: "Mystery/Thriller" },
  { title: "The Maidens", author: "Alex Michaelides", genre: "Mystery/Thriller" },
  { title: "In the Woods", author: "Tana French", genre: "Mystery/Thriller" },
  { title: "The Secret History", author: "Donna Tartt", genre: "Mystery/Thriller" },
  { title: "And Then There Were None", author: "Agatha Christie", genre: "Mystery/Thriller" },
  { title: "The Thursday Murder Club", author: "Richard Osman", genre: "Mystery/Thriller" },
  { title: "Verity", author: "Colleen Hoover", genre: "Mystery/Thriller" },
  { title: "The 7½ Deaths of Evelyn Hardcastle", author: "Stuart Turton", genre: "Mystery/Thriller" },
  // NEW Mystery/Thriller
  { title: "Murder on the Orient Express", author: "Agatha Christie", genre: "Mystery/Thriller" },
  { title: "The Murder of Roger Ackroyd", author: "Agatha Christie", genre: "Mystery/Thriller" },
  { title: "The ABC Murders", author: "Agatha Christie", genre: "Mystery/Thriller" },
  { title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", genre: "Mystery/Thriller" },
  { title: "The Girl on the Train", author: "Paula Hawkins", genre: "Mystery/Thriller" },
  { title: "Into the Water", author: "Paula Hawkins", genre: "Mystery/Thriller" },
  { title: "Big Little Lies", author: "Liane Moriarty", genre: "Mystery/Thriller" },
  { title: "Nine Perfect Strangers", author: "Liane Moriarty", genre: "Mystery/Thriller" },
  { title: "The Maid", author: "Nita Prose", genre: "Mystery/Thriller" },
  { title: "The Likeness", author: "Tana French", genre: "Mystery/Thriller" },
  { title: "The Wych Elm", author: "Tana French", genre: "Mystery/Thriller" },
  { title: "The Da Vinci Code", author: "Dan Brown", genre: "Mystery/Thriller" },
  { title: "Angels & Demons", author: "Dan Brown", genre: "Mystery/Thriller" },
  { title: "The Girl with the Louding Voice", author: "Abi Dare", genre: "Mystery/Thriller" },
  { title: "The Guest List", author: "Lucy Foley", genre: "Mystery/Thriller" },
  { title: "The Hunting Party", author: "Lucy Foley", genre: "Mystery/Thriller" },
  { title: "The Paris Apartment", author: "Lucy Foley", genre: "Mystery/Thriller" },
  { title: "One of Us Is Lying", author: "Karen M. McManus", genre: "Mystery/Thriller" },
  { title: "Two Can Keep a Secret", author: "Karen M. McManus", genre: "Mystery/Thriller" },
  { title: "The Woman in White", author: "Wilkie Collins", genre: "Mystery/Thriller" },
  { title: "The No. 1 Ladies' Detective Agency", author: "Alexander McCall Smith", genre: "Mystery/Thriller" },
  { title: "In the Blood", author: "Jack Carr", genre: "Mystery/Thriller" },
  { title: "The Couple Next Door", author: "Shari Lapena", genre: "Mystery/Thriller" },
  { title: "The Last Thing He Told Me", author: "Laura Dave", genre: "Mystery/Thriller" },
  { title: "The Sanatorium", author: "Sarah Pearse", genre: "Mystery/Thriller" },
  { title: "An Anonymous Girl", author: "Greer Hendricks", genre: "Mystery/Thriller" },
  { title: "The Night She Disappeared", author: "Lisa Jewell", genre: "Mystery/Thriller" },
  { title: "Then She Was Gone", author: "Lisa Jewell", genre: "Mystery/Thriller" },
  { title: "The Family Upstairs", author: "Lisa Jewell", genre: "Mystery/Thriller" },
  { title: "The Only Good Indians", author: "Stephen Graham Jones", genre: "Mystery/Thriller" },
  { title: "Rock Paper Scissors", author: "Alice Feeney", genre: "Mystery/Thriller" },
  { title: "Sometimes I Lie", author: "Alice Feeney", genre: "Mystery/Thriller" },
  { title: "A Good Girl's Guide to Murder", author: "Holly Jackson", genre: "Mystery/Thriller" },
  { title: "The Whisper Man", author: "Alex North", genre: "Mystery/Thriller" },
  { title: "The It Girl", author: "Ruth Ware", genre: "Mystery/Thriller" },
  { title: "The Woman in Cabin 10", author: "Ruth Ware", genre: "Mystery/Thriller" },
  { title: "One by One", author: "Ruth Ware", genre: "Mystery/Thriller" },
  { title: "The Turn of the Key", author: "Ruth Ware", genre: "Mystery/Thriller" },
  { title: "The Chain", author: "Adrian McKinty", genre: "Mystery/Thriller" },
  { title: "My Lovely Wife", author: "Samantha Downing", genre: "Mystery/Thriller" },
  { title: "The Devotion of Suspect X", author: "Keigo Higashino", genre: "Mystery/Thriller" },

  // ===================
  // Historical Fiction (~50)
  // ===================
  { title: "The Pillars of the Earth", author: "Ken Follett", genre: "Historical Fiction" },
  { title: "All the Light We Cannot See", author: "Anthony Doerr", genre: "Historical Fiction" },
  { title: "The Alice Network", author: "Kate Quinn", genre: "Historical Fiction" },
  { title: "The Rose Code", author: "Kate Quinn", genre: "Historical Fiction" },
  { title: "The Nightingale", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "The Four Winds", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "Outlander", author: "Diana Gabaldon", genre: "Historical Fiction" },
  { title: "Lincoln in the Bardo", author: "George Saunders", genre: "Historical Fiction" },
  { title: "The Name of the Rose", author: "Umberto Eco", genre: "Historical Fiction" },
  { title: "Wolf Hall", author: "Hilary Mantel", genre: "Historical Fiction" },
  { title: "The Kite Runner", author: "Khaled Hosseini", genre: "Historical Fiction" },
  { title: "A Thousand Splendid Suns", author: "Khaled Hosseini", genre: "Historical Fiction" },
  { title: "The Book Thief", author: "Markus Zusak", genre: "Historical Fiction" },
  // NEW Historical Fiction
  { title: "The Tattooist of Auschwitz", author: "Heather Morris", genre: "Historical Fiction" },
  { title: "The Help", author: "Kathryn Stockett", genre: "Historical Fiction" },
  { title: "Memoirs of a Geisha", author: "Arthur Golden", genre: "Historical Fiction" },
  { title: "The Shadow of the Wind", author: "Carlos Ruiz Zafon", genre: "Historical Fiction" },
  { title: "Shogun", author: "James Clavell", genre: "Historical Fiction" },
  { title: "Gone with the Wind", author: "Margaret Mitchell", genre: "Historical Fiction" },
  { title: "A Tale of Two Cities", author: "Charles Dickens", genre: "Historical Fiction" },
  { title: "War and Peace", author: "Leo Tolstoy", genre: "Historical Fiction" },
  { title: "Anna Karenina", author: "Leo Tolstoy", genre: "Historical Fiction" },
  { title: "The Count of Monte Cristo", author: "Alexandre Dumas", genre: "Historical Fiction" },
  { title: "The Three Musketeers", author: "Alexandre Dumas", genre: "Historical Fiction" },
  { title: "Bring Up the Bodies", author: "Hilary Mantel", genre: "Historical Fiction" },
  { title: "The Underground Railroad", author: "Colson Whitehead", genre: "Historical Fiction" },
  { title: "The Water Dancer", author: "Ta-Nehisi Coates", genre: "Historical Fiction" },
  { title: "Lilac Girls", author: "Martha Hall Kelly", genre: "Historical Fiction" },
  { title: "The Huntress", author: "Kate Quinn", genre: "Historical Fiction" },
  { title: "The Women", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "The Great Alone", author: "Kristin Hannah", genre: "Historical Fiction" },
  { title: "Beneath a Scarlet Sky", author: "Mark Sullivan", genre: "Historical Fiction" },
  { title: "City of Thieves", author: "David Benioff", genre: "Historical Fiction" },
  { title: "The Guernsey Literary and Potato Peel Pie Society", author: "Mary Ann Shaffer", genre: "Historical Fiction" },
  { title: "The Personal Librarian", author: "Marie Benedict", genre: "Historical Fiction" },
  { title: "The Paris Wife", author: "Paula McLain", genre: "Historical Fiction" },
  { title: "A Gentleman in Moscow", author: "Amor Towles", genre: "Historical Fiction" },
  { title: "The Lincoln Highway", author: "Amor Towles", genre: "Historical Fiction" },
  { title: "Rules of Civility", author: "Amor Towles", genre: "Historical Fiction" },
  { title: "The Island of Sea Women", author: "Lisa See", genre: "Historical Fiction" },
  { title: "Snow Flower and the Secret Fan", author: "Lisa See", genre: "Historical Fiction" },
  { title: "The Miniaturist", author: "Jessie Burton", genre: "Historical Fiction" },
  { title: "The Essex Serpent", author: "Sarah Perry", genre: "Historical Fiction" },
  { title: "Shantaram", author: "Gregory David Roberts", genre: "Historical Fiction" },
  { title: "The Things They Carried", author: "Tim O'Brien", genre: "Historical Fiction" },
  { title: "Cold Mountain", author: "Charles Frazier", genre: "Historical Fiction" },
  { title: "The Dovekeepers", author: "Alice Hoffman", genre: "Historical Fiction" },
  { title: "The Invention of Wings", author: "Sue Monk Kidd", genre: "Historical Fiction" },
  { title: "The Joy Luck Club", author: "Amy Tan", genre: "Historical Fiction" },
  { title: "The Kitchen God's Wife", author: "Amy Tan", genre: "Historical Fiction" },

  // ===================
  // YA (~50)
  // ===================
  { title: "The Hunger Games", author: "Suzanne Collins", genre: "YA" },
  { title: "Catching Fire", author: "Suzanne Collins", genre: "YA" },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", genre: "YA" },
  { title: "The Fault in Our Stars", author: "John Green", genre: "YA" },
  { title: "Turtles All the Way Down", author: "John Green", genre: "YA" },
  { title: "The Perks of Being a Wallflower", author: "Stephen Chbosky", genre: "YA" },
  { title: "Six of Crows", author: "Leigh Bardugo", genre: "YA" },
  { title: "Shadow and Bone", author: "Leigh Bardugo", genre: "YA" },
  { title: "An Ember in the Ashes", author: "Sabaa Tahir", genre: "YA" },
  { title: "The Cruel Prince", author: "Holly Black", genre: "YA" },
  { title: "Children of Blood and Bone", author: "Tomi Adeyemi", genre: "YA" },
  { title: "They Both Die at the End", author: "Adam Silvera", genre: "YA" },
  { title: "Eleanor & Park", author: "Rainbow Rowell", genre: "YA" },
  { title: "The Maze Runner", author: "James Dashner", genre: "YA" },
  // NEW YA
  { title: "Harry Potter and the Chamber of Secrets", author: "J.K. Rowling", genre: "YA" },
  { title: "Harry Potter and the Prisoner of Azkaban", author: "J.K. Rowling", genre: "YA" },
  { title: "Harry Potter and the Goblet of Fire", author: "J.K. Rowling", genre: "YA" },
  { title: "Harry Potter and the Order of the Phoenix", author: "J.K. Rowling", genre: "YA" },
  { title: "Harry Potter and the Half-Blood Prince", author: "J.K. Rowling", genre: "YA" },
  { title: "Harry Potter and the Deathly Hallows", author: "J.K. Rowling", genre: "YA" },
  { title: "Divergent", author: "Veronica Roth", genre: "YA" },
  { title: "Insurgent", author: "Veronica Roth", genre: "YA" },
  { title: "The Giver", author: "Lois Lowry", genre: "YA" },
  { title: "Mockingjay", author: "Suzanne Collins", genre: "YA" },
  { title: "Twilight", author: "Stephenie Meyer", genre: "YA" },
  { title: "New Moon", author: "Stephenie Meyer", genre: "YA" },
  { title: "The Lightning Thief", author: "Rick Riordan", genre: "YA" },
  { title: "The Sea of Monsters", author: "Rick Riordan", genre: "YA" },
  { title: "Fangirl", author: "Rainbow Rowell", genre: "YA" },
  { title: "The Hate U Give", author: "Angie Thomas", genre: "YA" },
  { title: "On the Come Up", author: "Angie Thomas", genre: "YA" },
  { title: "Crooked Kingdom", author: "Leigh Bardugo", genre: "YA" },
  { title: "King of Scars", author: "Leigh Bardugo", genre: "YA" },
  { title: "Ninth House", author: "Leigh Bardugo", genre: "YA" },
  { title: "The Wicked King", author: "Holly Black", genre: "YA" },
  { title: "The Queen of Nothing", author: "Holly Black", genre: "YA" },
  { title: "Simon vs. the Homo Sapiens Agenda", author: "Becky Albertalli", genre: "YA" },
  { title: "Leah on the Offbeat", author: "Becky Albertalli", genre: "YA" },
  { title: "To All the Boys I've Loved Before", author: "Jenny Han", genre: "YA" },
  { title: "The Sun Is Also a Star", author: "Nicola Yoon", genre: "YA" },
  { title: "Everything, Everything", author: "Nicola Yoon", genre: "YA" },
  { title: "Looking for Alaska", author: "John Green", genre: "YA" },
  { title: "Paper Towns", author: "John Green", genre: "YA" },
  { title: "Cinder", author: "Marissa Meyer", genre: "YA" },
  { title: "Miss Peregrine's Home for Peculiar Children", author: "Ransom Riggs", genre: "YA" },
  { title: "The Selection", author: "Kiera Cass", genre: "YA" },
  { title: "Scythe", author: "Neal Shusterman", genre: "YA" },
  { title: "Legendborn", author: "Tracy Deonn", genre: "YA" },
  { title: "The Ballad of Songbirds and Snakes", author: "Suzanne Collins", genre: "YA" },
  { title: "We Were Liars", author: "E. Lockhart", genre: "YA" },

  // ===================
  // Horror/Gothic (~40)
  // ===================
  { title: "Frankenstein", author: "Mary Shelley", genre: "Horror/Gothic" },
  { title: "Dracula", author: "Bram Stoker", genre: "Horror/Gothic" },
  { title: "The Haunting of Hill House", author: "Shirley Jackson", genre: "Horror/Gothic" },
  { title: "We Have Always Lived in the Castle", author: "Shirley Jackson", genre: "Horror/Gothic" },
  { title: "The Shining", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "It", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Pet Sematary", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", genre: "Horror/Gothic" },
  { title: "Plain Bad Heroines", author: "Emily M. Danforth", genre: "Horror/Gothic" },
  { title: "The Troop", author: "Nick Cutter", genre: "Horror/Gothic" },
  { title: "My Best Friend's Exorcism", author: "Grady Hendrix", genre: "Horror/Gothic" },
  { title: "House of Leaves", author: "Mark Z. Danielewski", genre: "Horror/Gothic" },
  { title: "Rebecca", author: "Daphne du Maurier", genre: "Horror/Gothic" },
  // NEW Horror/Gothic
  { title: "Misery", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Salem's Lot", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Carrie", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "The Stand", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "Doctor Sleep", author: "Stephen King", genre: "Horror/Gothic" },
  { title: "The Exorcist", author: "William Peter Blatty", genre: "Horror/Gothic" },
  { title: "The Silence of the Lambs", author: "Thomas Harris", genre: "Horror/Gothic" },
  { title: "Interview with the Vampire", author: "Anne Rice", genre: "Horror/Gothic" },
  { title: "The Vampire Lestat", author: "Anne Rice", genre: "Horror/Gothic" },
  { title: "Rosemary's Baby", author: "Ira Levin", genre: "Horror/Gothic" },
  { title: "The Stepford Wives", author: "Ira Levin", genre: "Horror/Gothic" },
  { title: "Bird Box", author: "Josh Malerman", genre: "Horror/Gothic" },
  { title: "The Turn of the Screw", author: "Henry James", genre: "Horror/Gothic" },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde", genre: "Horror/Gothic" },
  { title: "Coraline", author: "Neil Gaiman", genre: "Horror/Gothic" },
  { title: "The Graveyard Book", author: "Neil Gaiman", genre: "Horror/Gothic" },
  { title: "The Other", author: "Thomas Tryon", genre: "Horror/Gothic" },
  { title: "Hex", author: "Thomas Olde Heuvelt", genre: "Horror/Gothic" },
  { title: "The Southern Book Club's Guide to Slaying Vampires", author: "Grady Hendrix", genre: "Horror/Gothic" },
  { title: "Horrorstör", author: "Grady Hendrix", genre: "Horror/Gothic" },
  { title: "The Cabin at the End of the World", author: "Paul Tremblay", genre: "Horror/Gothic" },
  { title: "A Head Full of Ghosts", author: "Paul Tremblay", genre: "Horror/Gothic" },
  { title: "The Woman in Black", author: "Susan Hill", genre: "Horror/Gothic" },
  { title: "The Changeling", author: "Victor LaValle", genre: "Horror/Gothic" },
  { title: "Bunny", author: "Mona Awad", genre: "Horror/Gothic" },
  { title: "The Elementals", author: "Michael McDowell", genre: "Horror/Gothic" },
  { title: "Ghost Story", author: "Peter Straub", genre: "Horror/Gothic" },

  // ===================
  // Nonfiction/Memoir (~40) — NEW
  // ===================
  { title: "Educated", author: "Tara Westover", genre: "Nonfiction/Memoir" },
  { title: "Becoming", author: "Michelle Obama", genre: "Nonfiction/Memoir" },
  { title: "The Glass Castle", author: "Jeannette Walls", genre: "Nonfiction/Memoir" },
  { title: "When Breath Becomes Air", author: "Paul Kalanithi", genre: "Nonfiction/Memoir" },
  { title: "Sapiens", author: "Yuval Noah Harari", genre: "Nonfiction/Memoir" },
  { title: "Homo Deus", author: "Yuval Noah Harari", genre: "Nonfiction/Memoir" },
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", genre: "Nonfiction/Memoir" },
  { title: "Atomic Habits", author: "James Clear", genre: "Nonfiction/Memoir" },
  { title: "The Body Keeps the Score", author: "Bessel van der Kolk", genre: "Nonfiction/Memoir" },
  { title: "Born a Crime", author: "Trevor Noah", genre: "Nonfiction/Memoir" },
  { title: "Between the World and Me", author: "Ta-Nehisi Coates", genre: "Nonfiction/Memoir" },
  { title: "Just Mercy", author: "Bryan Stevenson", genre: "Nonfiction/Memoir" },
  { title: "Crying in H Mart", author: "Michelle Zauner", genre: "Nonfiction/Memoir" },
  { title: "The Immortal Life of Henrietta Lacks", author: "Rebecca Skloot", genre: "Nonfiction/Memoir" },
  { title: "In Cold Blood", author: "Truman Capote", genre: "Nonfiction/Memoir" },
  { title: "Into the Wild", author: "Jon Krakauer", genre: "Nonfiction/Memoir" },
  { title: "Into Thin Air", author: "Jon Krakauer", genre: "Nonfiction/Memoir" },
  { title: "The Devil in the White City", author: "Erik Larson", genre: "Nonfiction/Memoir" },
  { title: "Quiet", author: "Susan Cain", genre: "Nonfiction/Memoir" },
  { title: "Outliers", author: "Malcolm Gladwell", genre: "Nonfiction/Memoir" },
  { title: "The Tipping Point", author: "Malcolm Gladwell", genre: "Nonfiction/Memoir" },
  { title: "Blink", author: "Malcolm Gladwell", genre: "Nonfiction/Memoir" },
  { title: "Man's Search for Meaning", author: "Viktor E. Frankl", genre: "Nonfiction/Memoir" },
  { title: "The Diary of a Young Girl", author: "Anne Frank", genre: "Nonfiction/Memoir" },
  { title: "I Know Why the Caged Bird Sings", author: "Maya Angelou", genre: "Nonfiction/Memoir" },
  { title: "Night", author: "Elie Wiesel", genre: "Nonfiction/Memoir" },
  { title: "Wild", author: "Cheryl Strayed", genre: "Nonfiction/Memoir" },
  { title: "Eat, Pray, Love", author: "Elizabeth Gilbert", genre: "Nonfiction/Memoir" },
  { title: "The Year of Magical Thinking", author: "Joan Didion", genre: "Nonfiction/Memoir" },
  { title: "Know My Name", author: "Chanel Miller", genre: "Nonfiction/Memoir" },
  { title: "Greenlights", author: "Matthew McConaughey", genre: "Nonfiction/Memoir" },
  { title: "A Promised Land", author: "Barack Obama", genre: "Nonfiction/Memoir" },
  { title: "The Autobiography of Malcolm X", author: "Malcolm X", genre: "Nonfiction/Memoir" },
  { title: "Long Walk to Freedom", author: "Nelson Mandela", genre: "Nonfiction/Memoir" },
  { title: "Shoe Dog", author: "Phil Knight", genre: "Nonfiction/Memoir" },
  { title: "Bad Blood", author: "John Carreyrou", genre: "Nonfiction/Memoir" },
  { title: "Unbroken", author: "Laura Hillenbrand", genre: "Nonfiction/Memoir" },
  { title: "Seabiscuit", author: "Laura Hillenbrand", genre: "Nonfiction/Memoir" },
  { title: "The Power of Habit", author: "Charles Duhigg", genre: "Nonfiction/Memoir" },
  { title: "Maybe You Should Talk to Someone", author: "Lori Gottlieb", genre: "Nonfiction/Memoir" },

  // ===================
  // Contemporary Fiction (~40) — NEW
  // ===================
  { title: "The Midnight Library", author: "Matt Haig", genre: "Contemporary Fiction" },
  { title: "Eleanor Oliphant Is Completely Fine", author: "Gail Honeyman", genre: "Contemporary Fiction" },
  { title: "A Man Called Ove", author: "Fredrik Backman", genre: "Contemporary Fiction" },
  { title: "Anxious People", author: "Fredrik Backman", genre: "Contemporary Fiction" },
  { title: "Beartown", author: "Fredrik Backman", genre: "Contemporary Fiction" },
  { title: "Little Fires Everywhere", author: "Celeste Ng", genre: "Contemporary Fiction" },
  { title: "Everything I Never Told You", author: "Celeste Ng", genre: "Contemporary Fiction" },
  { title: "Our Missing Hearts", author: "Celeste Ng", genre: "Contemporary Fiction" },
  { title: "Such a Fun Age", author: "Kiley Reid", genre: "Contemporary Fiction" },
  { title: "The Great Believers", author: "Rebecca Makkai", genre: "Contemporary Fiction" },
  { title: "Olive, Again", author: "Elizabeth Strout", genre: "Contemporary Fiction" },
  { title: "Oh William!", author: "Elizabeth Strout", genre: "Contemporary Fiction" },
  { title: "Commonwealth", author: "Ann Patchett", genre: "Contemporary Fiction" },
  { title: "Tom Lake", author: "Ann Patchett", genre: "Contemporary Fiction" },
  { title: "The Light We Lost", author: "Jill Santopolo", genre: "Contemporary Fiction" },
  { title: "The Storied Life of A.J. Fikry", author: "Gabrielle Zevin", genre: "Contemporary Fiction" },
  { title: "Less", author: "Andrew Sean Greer", genre: "Contemporary Fiction" },
  { title: "The Curious Incident of the Dog in the Night-Time", author: "Mark Haddon", genre: "Contemporary Fiction" },
  { title: "Room", author: "Emma Donoghue", genre: "Contemporary Fiction" },
  { title: "The Lovely Bones", author: "Alice Sebold", genre: "Contemporary Fiction" },
  { title: "The Time Traveler's Wife", author: "Audrey Niffenegger", genre: "Contemporary Fiction" },
  { title: "The Alchemist", author: "Paulo Coelho", genre: "Contemporary Fiction" },
  { title: "The House of the Spirits", author: "Isabel Allende", genre: "Contemporary Fiction" },
  { title: "White Oleander", author: "Janet Fitch", genre: "Contemporary Fiction" },
  { title: "The Memory Police", author: "Yoko Ogawa", genre: "Contemporary Fiction" },
  { title: "Convenience Store Woman", author: "Sayaka Murata", genre: "Contemporary Fiction" },
  { title: "Breasts and Eggs", author: "Mieko Kawakami", genre: "Contemporary Fiction" },
  { title: "The Interpreter of Maladies", author: "Jhumpa Lahiri", genre: "Contemporary Fiction" },
  { title: "The Namesake", author: "Jhumpa Lahiri", genre: "Contemporary Fiction" },
  { title: "Small Things Like These", author: "Claire Keegan", genre: "Contemporary Fiction" },
  { title: "Foster", author: "Claire Keegan", genre: "Contemporary Fiction" },
  { title: "Detransition, Baby", author: "Torrey Peters", genre: "Contemporary Fiction" },
  { title: "The House of Mirth", author: "Edith Wharton", genre: "Contemporary Fiction" },
  { title: "The Age of Innocence", author: "Edith Wharton", genre: "Contemporary Fiction" },
  { title: "North and South", author: "Elizabeth Gaskell", genre: "Contemporary Fiction" },
  { title: "Extremely Loud and Incredibly Close", author: "Jonathan Safran Foer", genre: "Contemporary Fiction" },
  { title: "Everything Is Illuminated", author: "Jonathan Safran Foer", genre: "Contemporary Fiction" },
  { title: "We Need to Talk About Kevin", author: "Lionel Shriver", genre: "Contemporary Fiction" },
  { title: "The Bell Jar", author: "Sylvia Plath", genre: "Contemporary Fiction" },
  { title: "Fight Club", author: "Chuck Palahniuk", genre: "Contemporary Fiction" },
];
